name: Go-Linux

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-linux.yml'
      - '**.go'
      - '**.yml'
      - '**.R'
      - '**.Rmd'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-linux.yml'
      - '**.go'
      - '**.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: ./analysis/report

    - name: Fetch Docker test-image
      run: docker image pull hello-world

    - name: Fetch Docker alpine-image
      run: docker image pull alpine

    - name: Fetch Prometheus image
      run: docker image pull prom/prometheus:v2.44.0

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./
        tags: opera
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    # This ugly bit is necessary if you don't want your cache to grow forever
    # until it hits GitHub's limit of 5GB.
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Build
      working-directory: ./
      run: go build -v ./...

    - name: Test
      working-directory: ./
      run: go test -count=1 ./...
