name: Go-Linux

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-linux.yml'
      - '**.go'
      - '**.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-linux.yml'
      - '**.go'
      - '**.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Fetch Docker test-image
      run: docker image pull hello-world

    - name: Fetch Docker alpine-image
      run: docker image pull alpine

    - name: Build Docker Image
      working-directory: ./
      run: docker build . -t opera

    - name: Build
      working-directory: ./
      run: go build -v ./...

    - name: Test
      working-directory: ./
      run: go test -v ./...
