name: Go-OSX

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-osx.yml'
      - '**.go'

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
#        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v1
      with:
        version: v23.0.4

    - name: Build Docker Image
      working-directory: ./
      run: docker build . -t opera
      
    - name: Build
      working-directory: ./
      run: go build -v ./...

    - name: Test
      working-directory: ./
      run: go test -v ./...
