name: Go-OSX

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-osx.yml'
      - '**.go'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/go-osx.yml'

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up Docker
      run: |
        brew install docker
        colima start --memory 8

    - name: Fetch Docker test-image
      run: docker image pull hello-world

      # Cache of docker layers
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build Docker Image
      working-directory: ./
      run: docker build . -t opera
  
    - name: Build
      working-directory: ./
      run: go build -v ./...

    - name: Test
      working-directory: ./
      run: go test -v ./...
      env:
        DOCKER_HOST: "unix:///Users/runner/.colima/default/docker.sock"
